### ISSUE TITLE
Import

### ISSUE THREAD

**Issue by JELollis** [JELollis/BardBot#1]
When launching, current version is non-functional. Errors on all included imports with current version of Discord.py

```
Traceback (most recent call last): 
 File "/BardBot/BardBot_Discord.py", line 2, in <module> 
   from discord_slash import SlashCommand 
 File "~/.local/lib/python3.10/site-packages/discord_slash/__init__.py", line 9, 
in <module> 
   from .client import SlashCommand  # noqa: F401 
 File "~/.local/lib/python3.10/site-packages/discord_slash/client.py", line 12, i
n <module> 
   from . import context, error, http, model 
 File "~/.local/lib/python3.10/site-packages/discord_slash/context.py", line 10, 
in <module> 
   from . import error, http, model 
 File "~/.local/lib/python3.10/site-packages/discord_slash/model.py", line 12, in
<module> 
   from .dpy_overrides import ComponentMessage 
 File "~/.local/lib/python3.10/site-packages/discord_slash/dpy_overrides.py", lin
e 4, in <module> 
   from discord import AllowedMentions, File, InvalidArgument, abc, http, utils 
ImportError: cannot import name 'InvalidArgument' from 'discord' (~/.local/lib/pyt
hon3.10/site-packages/discord/__init__.py)
```

**Comment by JELollis** [comment]
Issue corrected. Closing.
